"""add_struct_fields

Revision ID: a9ad3f86020c
Revises: 6a5b7726a9b5
Create Date: 2026-01-15 14:05:46.116260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ad3f86020c'
down_revision: Union[str, Sequence[str], None] = '6a5b7726a9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('exercise', sa.String(), nullable=True))
    op.add_column('workout_logs', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('workout_logs', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('workout_logs', sa.Column('reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'reps')
    op.drop_column('workout_logs', 'sets')
    op.drop_column('workout_logs', 'weight')
    op.drop_column('workout_logs', 'exercise')
    # ### end Alembic commands ###
